import { test, expect } from '@playwright/test'

test('mobile objects move with scroll and respond to a finger drag without opening', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
  const page = await context.newPage()
  const devtools = await context.newCDPSession(page)
  await page.goto('/')

  const object = page.locator('#object-link-about')
  const initialOffset = await object.evaluate(element => getComputedStyle(element).getPropertyValue('--scroll-y'))
  await page.evaluate(() => window.scrollTo(0, 350))
  await expect.poll(() => object.evaluate(element => getComputedStyle(element).getPropertyValue('--scroll-y'))).not.toBe(initialOffset)

  await page.evaluate(() => window.scrollTo(0, 0))
  await object.scrollIntoViewIfNeeded()
  const swipeBounds = await object.boundingBox()
  expect(swipeBounds).not.toBeNull()
  const swipeX = Math.round(swipeBounds!.x + swipeBounds!.width / 2)
  const swipeY = Math.round(swipeBounds!.y + swipeBounds!.height / 2)
  const scrollBeforeSwipe = await page.evaluate(() => window.scrollY)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: swipeX, y: swipeY }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: swipeX, y: swipeY - 40 }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: swipeX, y: swipeY - 110 }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(scrollBeforeSwipe)

  await object.scrollIntoViewIfNeeded()
  const bounds = await object.boundingBox()
  expect(bounds).not.toBeNull()
  const x = Math.round(bounds!.x + bounds!.width / 2)
  const y = Math.round(bounds!.y + bounds!.height / 2)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 60, y }] })
  await expect(object).toHaveAttribute('data-touch-dragging', 'true')
  expect(await object.evaluate(element => element.style.getPropertyValue('--touch-x'))).not.toBe('')
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(object).not.toHaveAttribute('data-touch-dragging', 'true')
  await expect(page).toHaveURL(/\/$/)

  await object.tap()
  await expect(page).toHaveURL(/#\/item\/about$/)
  await context.close()
})

test('mobile record can be dragged and the graph returns to its resting shape', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
  const page = await context.newPage()
  const devtools = await context.newCDPSession(page)
  await page.goto('/#/item/record')
  const record = page.locator('.detail-art-wrap .artwork-record')
  const bounds = await record.boundingBox()
  expect(bounds).not.toBeNull()
  const x = Math.round(bounds!.x + bounds!.width / 2)
  const y = Math.round(bounds!.y + bounds!.height / 2)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 70, y }] })
  await expect(page.locator('.detail-art-wrap .vinyl')).toHaveCSS('--record-angle', '70deg')
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })

  await page.goto('/')
  const graph = page.locator('#object-link-graph .graph-artwork-interaction')
  await graph.scrollIntoViewIfNeeded()
  const restingCurve = await graph.locator('.graph-curve').getAttribute('d')
  const graphBounds = await graph.boundingBox()
  expect(graphBounds).not.toBeNull()
  const graphX = Math.round(graphBounds!.x + graphBounds!.width / 2)
  const graphY = Math.round(graphBounds!.y + graphBounds!.height / 2)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: graphX, y: graphY }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: graphX + 30, y: graphY }] })
  await expect.poll(() => graph.locator('.graph-curve').getAttribute('d')).not.toBe(restingCurve)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(graph.locator('.graph-curve')).toHaveAttribute('d', restingCurve ?? '')
  await context.close()
})

test('detail graph follows a finger drag and settles after release', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true })
  const page = await context.newPage()
  const devtools = await context.newCDPSession(page)
  await page.goto('/#/item/graph')

  const graph = page.locator('.detail-art-graph .graph-artwork-interaction')
  const curve = graph.locator('.graph-curve')
  const restingCurve = await curve.getAttribute('d')
  const bounds = await graph.boundingBox()
  expect(bounds).not.toBeNull()
  const x = Math.round(bounds!.x + bounds!.width / 2)
  const y = Math.round(bounds!.y + bounds!.height / 2)

  await devtools.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 30, y: y + 20 }] })
  await expect.poll(() => curve.getAttribute('d')).not.toBe(restingCurve)
  await devtools.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(curve).toHaveAttribute('d', restingCurve ?? '')

  await context.close()
})
